# onSaveGeneralConsent() {
#     const obj = { 'TCRMService': {
#         '@schemaLocation': 'http://www.ibm.com/mdm/schema MDMDomains.xsd',
#         'RequestControl': {
#           'requestID': '10015',
#           'DWLControl': {
#             'requesterName': 'cusadmin',
#             'requesterLanguage': '100'
#           }
#         },
#         'TCRMTx': {
#           'TCRMTxType': 'addConsent',
#           'TCRMTxObject': 'ConsentBObj',
#           'TCRMObject': {
#             'ConsentBObj': {
#               'ConsentOwnerId': amary@gmail.com,
#               'ProcPurpId': '728153040827580997',
#               'AgreeInd': '1',
#               'LanguageAgreedInType': '100',
#               'EnforcementType': '2',
#               'CreateDate': '2017-07-15',
#               'StartDate': '2017-07-15',
#               'ProfileSystemType': '2'
#             }
#           }
#         }
#       }
#     };

#     const httpOptions = {
#       headers: new HttpHeaders({
#         Content-Type: application/json,
#         Accept: application/json,
#         Authorization: Basic bWRtYWRtaW46bWRtYWRtaW4=
#       })
#     };

#     this.httpClient
#     .put('/api/com.ibm.mdm.server.ws.restful/resources/MDMWSRESTful', obj, httpOptions)
#     .subscribe(data => {
#         console.log( 'les donnes de retour de la requete : ' + data);
#     }, error => {
#       console.log('les erreurs : ' + error);
#     });
#   }
# }




PUT http://mdmdemowin:9080/com.ibm.mdm.server.ws.restful/resources/MDMWSRESTful
Content-Type: application/json
Accept: application/json
Authorization: Basic bWRtYWRtaW46bWRtYWRtaW4=

{"TCRMService":{
    "@schemaLocation":"http:\/\/www.ibm.com\/mdm\/schema MDMDomains.xsd",
    "RequestControl":{
        "requestID":"10015",
        "DWLControl":{
            "requesterName":"cusadmin",
            "requesterLanguage":"100"
            }
            },
            "TCRMTx":{
                "TCRMTxType":"addConsent",
                "TCRMTxObject":"ConsentBObj",
                "TCRMObject":{
                    "ConsentBObj":{
                        "ConsentOwnerId":"ad@a.com",
                        "ProcPurpId":"728153040827580997",
                        "AgreeInd":"1",
                        "LanguageAgreedInType":"100",
                        "EnforcementType":"2",
                        "CreateDate":"2017-07-15",
                        "StartDate":"2017-07-07",
                        "ProfileSystemType":"2"
                 }
            }
        }
    }
}
